FROM gradle:jdk21-alpine
ARG PRODUCTION
ARG JDBC_DATABASE_PASSWORD
ARG JDBC_DATABASE_URL
ARG JDBC_DATABASE_USERNAME
ARG AUTH_DOMAIN
ARG SONARCLOUD_TOKEN

ENV PRODUCTION ${PRODUCTION}
ENV JDBC_DATABASE_PASSWORD ${JDBC_DATABASE_PASSWORD}
ENV JDBC_DATABASE_URL ${JDBC_DATABASE_URL}
ENV JDBC_DATABASE_USERNAME ${JDBC_DATABASE_USERNAME}
ENV AUTH_DOMAIN ${AUTH_DOMAIN}
ENV SONARCLOUD_TOKEN ${SONARCLOUD_TOKEN}

WORKDIR /app
RUN ls -al
COPY ./AFK3-0.0.1-SNAPSHOT.jar /app
EXPOSE 8080
EXPOSE 3000
CMD ["java","-jar","AFK3-0.0.1-SNAPSHOT.jar"]
