scrape_configs:
  - job_name: 'AFK3Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['AFK3:8080']
        labels:
          application: 'AFK3'